{{/*
  Inputs:
  - name
  - secretStore
  - mappings
  - refreshInterval (default: 1h)
  - isClusterSecretStore
  - isRegistryCredential
*/}}

{{- define "common-templates.externalSecretStore.type" -}}
{{- if .isClusterSecretStore -}}Cluster{{- end }}SecretStore
{{- end }}

{{- define "common-templates.externalSecret.tpl" -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ default "1h" .refreshInterval }}
  secretStoreRef:
    kind: {{ include "common-templates.externalSecretStore.type" . }}
    name: {{ .secretStore }}
  target:
  {{- if .isRegistryCredential }}
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .imagepullsecret }}` }}"
  {{- end }}
    creationPolicy: Owner
  data:
  {{- if .isRegistryCredential }}
  - secretKey: imagepullsecret
    remoteRef:
      key: {{ values .mappings | first }}
  {{- else }}
    {{- range $key, $value := .mappings }}
  - secretKey: {{ $key }}
    remoteRef:
      key: {{ $value }}
    {{- end }}
  {{- end }}
{{- end }}
