---
common:
  labels: {}
  annotations: {}

  serviceAccount:
    {}

  secretStore:
    provider:
      azurekv:
        authType: WorkloadIdentity

  externalSecret:
    refreshInterval: 1h
    secretStoreRef:
      kind: SecretStore
    target:
      template: {}
      creationPolicy: Owner

  configMap:
    {}

  persistentVolumeClaim:
    storageClassName: managed-csi
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeMode: Filesystem

  container:
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]

  pod:
    labels: {}
    annotations: {}
    serviceAccountName: default
    automountServiceAccountToken: false
    hostAliases: []
    affinity: {}
    hostNetwork: false
    hostIPC: false
    dnsPolicy: ""
    dnsConfig: {}
    priorityClassName: ""
    nodeSelector: {}
    tolerations: []
    schedulerName: ""
    enableServiceLinks: false
    securityContext:
      seccompProfile:
        type: "RuntimeDefault"
    terminationGracePeriodSeconds: 30
    restartPolicy: Always
    initContainers: {}
    containers: {}
    volumes: []

  cronJob:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    suspend: false

  deployment:
    revisionHistoryLimit: 3
    strategy:
      type: RollingUpdate
    selector:
      matchLabels: {}
    pod: {}

  service:
    labels: {}
    annotations: {}
    type: ClusterIP
    clusterIP: ~
    sessionAffinity: ~
    sessionAffinityConfig: ~
    externalTrafficPolicy: Cluster
    loadBalancerSourceRanges: ~
    loadBalancerIP: ~
    loadBalancerClass: ~
    ports: []
    selector: {}

  podDisruptionBudget:
    maxUnavailable: 1
    unhealthyPodEvictionPolicy: AlwaysAllow
    selector: {}

  horizontalPodAutoscaler:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    minReplicas: 2
    maxReplicas: 10

  httpRoute:
    parentRefs: []

  ingress:
    ingressClassName: istio
    tls: []
    rules: []

  istioVirtualService:
    hosts: []
    gateways: []
    http: []

  istioGateway:
    selector:
      istio-gateway: gateway-internal
    targetRefs: []

  authorizationPolicy:
    action: ALLOW
    selector: {}
    targetRefs: []

  application:
    helm: {}
    syncPolicy:
      automated: {}

  certificate:
    issuerRef:
      name: hydrantid
      kind: ClusterIssuer
      group: cert-manager.io
    usages:
      - digital signature
      - key encipherment

  networkPolicy: {}

  vmAlertmanagerConfig: {}

  vmRule: {}

  hooks: {}
