---
global:
  supportedKinds:
    applications: [argoproj.io/v1alpha1, Application, application, true]
    authorizationPolicies: [security.istio.io/v1, AuthorizationPolicy, authorizationPolicy, false]
    certificates: [cert-manager.io/v1, Certificate, certificate, true]
    configMaps: [v1, ConfigMap, configMap, false]
    cronJobs: [batch/v1, CronJob, cronJob, true]
    deployments: [apps/v1, Deployment, deployment, true]
    externalSecrets: [external-secrets.io/v1beta1, ExternalSecret, externalSecret, true]
    horizontalPodAutoscalers: [autoscaling/v2, HorizontalPodAutoscaler, horizontalPodAutoscaler, false]
    httpRoutes: [gateway.networking.k8s.io/v1, HTTPRoute, httpRoute, true]
    ingresses: [networking.k8s.io/v1, Ingress, ingress, false]
    istioGateways: [networking.istio.io/v1, Gateway, istioGateway, false]
    istioVirtualServices: [networking.istio.io/v1beta1, VirtualService, istioVirtualService, false]
    networkPolicies: [networking.k8s.io/v1, NetworkPolicy, networkPolicy, false]
    persistentVolumeClaims: [v1, PersistentVolumeClaim, persistentVolumeClaim, false]
    pods: [v1, Pod, pod, true]
    podDisruptionBudgets: [policy/v1, PodDisruptionBudget, podDisruptionBudget, true]
    secretStores: [external-secrets.io/v1beta1, SecretStore, secretStore, false]
    services: [v1, Service, service, true]
    serviceAccounts: [v1, ServiceAccount, serviceAccount, false]
    vmAlertmanagerConfigs: [operator.victoriametrics.com/v1beta1, VMAlertmanagerConfig, vmAlertmanagerConfig, true]
    vmRules: [operator.victoriametrics.com/v1beta1, VMRule, vmRule, true]

common:
  labels: {}
  annotations: {}

  serviceAccount: {}

  secretStore:
    spec:
      provider:
        azurekv:
          authType: WorkloadIdentity

  externalSecret:
    spec:
      refreshInterval: 1h
      secretStoreRef:
        kind: SecretStore
      target:
        creationPolicy: Owner

  configMap: {}

  persistentVolumeClaim:
    spec:
      storageClassName: managed-csi
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      volumeMode: Filesystem

  container:
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]

  pod:
    spec:
      serviceAccountName: default
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30

  cronJob:
    spec:
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      jobTemplate:
        spec:
          template: {}

  deployment:
    spec:
      revisionHistoryLimit: 3
      strategy:
        type: RollingUpdate
      template: {}

  service: {}

  podDisruptionBudget:
    spec:
      maxUnavailable: 1
      unhealthyPodEvictionPolicy: AlwaysAllow

  horizontalPodAutoscaler:
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 75
      minReplicas: 2
      maxReplicas: 10

  httpRoute: {}

  ingress:
    spec:
      ingressClassName: istio

  istioVirtualService: {}

  istioGateway: {}

  authorizationPolicy: {}

  application:
    spec:
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated: {}

  certificate:
    spec:
      issuerRef:
        name: hydrantid
        kind: ClusterIssuer
        group: cert-manager.io
      usages:
        - digital signature
        - key encipherment

  networkPolicy: {}

  vmAlertmanagerConfig:
    spec:
      route:
        group_interval: 1m

  vmRule: {}

  hooks: {}
