---
common:
  labels: {}
  annotations: {}

  serviceAccount:
    {}

  secretStore:
    provider:
      azurekv:
        authType: WorkloadIdentity

  externalSecret:
    refreshInterval: 1h
    secretStoreRef:
      kind: SecretStore
    target:
      template: {}
      creationPolicy: Owner

  configMap:
    {}

  persistentVolumeClaim:
    storageClassName: managed-csi
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeMode: Filesystem

  container:
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]

  pod:
    labels: {}
    annotations: {}
    serviceAccountName: default
    automountServiceAccountToken: false
    enableServiceLinks: false
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    terminationGracePeriodSeconds: 30

  cronJob:
    concurrencyPolicy: Forbid
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 1
    suspend: false

  deployment:
    revisionHistoryLimit: 3
    strategy:
      type: RollingUpdate
    selector:
      matchLabels: {}
    pod: {}

  service: {}

  podDisruptionBudget:
    maxUnavailable: 1
    unhealthyPodEvictionPolicy: AlwaysAllow

  horizontalPodAutoscaler:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    minReplicas: 2
    maxReplicas: 10

  httpRoute: {}

  ingress:
    ingressClassName: istio

  istioVirtualService: {}

  istioGateway: {}

  authorizationPolicy:
    action: ALLOW
    selector: {}
    targetRefs: []

  application:
    helm: {}
    syncPolicy:
      automated: {}

  certificate:
    issuerRef:
      name: hydrantid
      kind: ClusterIssuer
      group: cert-manager.io
    usages:
      - digital signature
      - key encipherment

  networkPolicy: {}

  vmAlertmanagerConfig: {}

  vmRule: {}

  hooks: {}
