{{- if eq .Values.type "Pod" }}
{{- with .Values.pod }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Release.Name }}
  {{- include "common.metadata" . | nindent 2 }}
spec: {{- include "common.pod" . | nindent 2 }}
{{- end }}
{{- end }}
