{{- if eq .Values.type "Pod" }}
{{ $values = .Values }}
{{- with .Values.pod }}
---
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Release.Name }}
  {{- include "common.metadata" (merge dict . (dict "Values" .Values)) | nindent 2 }}
spec: {{- include "common.pod" . | nindent 2 }}
{{- end }}
{{- end }}
