{{- define "common.containers" -}}
{{- $common := .common }}
{{- $values := .Values }}
{{- range .containers }}
{{- with mergeOverwrite $common.container . }}
- name: {{ .name }}
  image: {{ tpl .image (dict "Values" $values "Template" (dict "BasePath" "<inline>" "Name" "<noname>")) }}
  imagePullPolicy: {{ .imagePullPolicy | quote }}
  {{- if .securityContext.enabled }}
  securityContext: {{- toYaml (omit .securityContext "enabled") | nindent 4 }}
  {{- end }}
  {{- if .env }}
  env: {{- toYaml .env | nindent 4 }}
  {{- end }}
  {{- if .command }}
  command: {{- toYaml .command | nindent 4 }}
  {{- end }}
  {{- if .args }}
  args: {{- toYaml .args | nindent 4 }}
  {{- end }}
  {{- if .lifecycleHooks }}
  lifecycle: {{- toYaml .lifecycleHooks | nindent 4 }}
  {{- end }}
  {{- if .ports }}
  ports: {{- toYaml .ports | nindent 4 }}
  {{- end }}
  {{- if .livenessProbe }}
  livenessProbe: {{- toYaml .livenessProbe | nindent 4 }}
  {{- end }}
  {{- if .readinessProbe }}
  readinessProbe: {{- toYaml .readinessProbe | nindent 4 }}
  {{- end }}
  {{- if .startupProbe }}
  startupProbe: {{- toYaml .startupProbe | nindent 4 }}
  {{- end }}
  {{- if .resources }}
  resources: {{- toYaml .resources | nindent 4 }}
  {{- end }}
  {{- if .volumeMounts }}
  volumeMounts: {{- toYaml .volumeMounts | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
