{{- define "common.pod" -}}
serviceAccountName: {{ .serviceAccount.name }}
automountServiceAccountToken: {{ .automountServiceAccountToken }}
{{- if .hostAliases }}
hostAliases: {{- toYaml .hostAliases | nindent 2 }}
{{- end }}
{{- if .affinity }}
affinity: {{- toYaml .affinity | nindent 2 }}
{{- end }}
hostNetwork: {{ .hostNetwork }}
hostIPC: {{ .hostIPC }}
{{- if .dnsPolicy  }}
dnsPolicy: {{ .dnsPolicy }}
{{- end }}
{{- if .dnsConfig }}
dnsConfig: {{- toYaml .dnsConfig | nindent 2 }}
{{- end }}
{{- if .priorityClassName }}
priorityClassName: {{ .priorityClassName | quote }}
{{- end }}
{{- if .nodeSelector }}
nodeSelector: {{- toYaml .nodeSelector | nindent 2 }}
{{- end }}
{{- if .tolerations }}
tolerations: {{- toYaml .tolerations | nindent 2 }}
{{- end }}
{{- if .schedulerName }}
schedulerName: {{ .schedulerName | quote }}
{{- end }}
{{- if .securityContext.enabled }}
securityContext: {{- toYaml (omit .securityContext "enabled") | nindent 2 }}
{{- end }}
{{- if .terminationGracePeriodSeconds }}
terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
{{- end }}
restartPolicy: {{ .restartPolicy }}
enableServiceLinks: false
{{- if .initContainers }}
initContainers: {{- include "common.containers" (dict "containers" (concat .common.pod.initContainers .initContainers) "common" .common) | default "[]" | nindent 2 }}
{{- end }}
containers: {{- include "common.containers" (dict "containers" (concat .common.pod.containers .containers) "common" .common) | default "[]" | nindent 2 }}
{{- if .volumes }}
volumes: {{- toYaml .volumes | nindent 2 }}
{{- end }}
{{- end }}
