---
# appName: xxx

common:
  labels: # {}
    c1: cv1
  annotations: # {}
    a1: av1

  container:
    securityContext:
      enabled: false
  pod:
    securityContext:
      enabled: false
    # containers:
    # - name: a2
    #   image: a2:latest

configMaps:
  # c0: ~
  c1:
    c1-f1.txt: |
      file c1-f1
    c1-f2.txt: |
      file c1-f2
  c2:
    c2-f1.txt: |
      file c2-f1

deployments:
  d1:
    labels:
      d: d1
    annotations:
      ad: d1
    pod:
      selectorLabels:
        app: app1
      labels:
        zz: z1
      containers:
      - name: c1
        image: c1:latest
        command: [/bin/run.sh]
        volumeMounts:
        - name: c1
          mountPath: /mnt/c1
      # - name: c2
      #   image: c2:latest
      # - name: c3
      #   image: c3:latest
      resources:
        limits:
          memory: 500Mi
          cpu: 300m
        requests:
          memory: 300Mi
          cpu: 100m

# services:
#   app1:
#     ports:
#     - name: http
#       port: 80
#       targetPort: 8080
#     - name: tls
#       port: 443
#       targetPort: 8443
#     selector:
#       app: app1

# deployments:
# - name: app1
#   containers:
#   - name: app
#     image: asd:latest
#   #   volumeMounts: []
#   # volumes: []
#   resources:
#     limits:
#       memory: 500Mi
#       cpu: 300m
#     requests:
#       memory: 300Mi
#       cpu: 100m

# services:
# - ports:
#   - port: 80
#     targetPort: 8080
#   - port: 443
#     targetPort: 8443
#   selector:
#     app: app1
