{{- if .Values.configSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gradle-cache.configSecretName" . }}
  labels:
    {{- include "gradle-cache.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.configSecret.content | b64enc | quote }}
{{- end }}  