{{- define "common.externalsecret" -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: {{- include "common.metadata" . | nindent 2 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .secretStore }}
    kind: SecretStore
  target:
    {{- if .target.template }}
    template: {{- toYaml .target.template | nindent 6 }}
    {{- end }}
    name: {{ .name }}
    creationPolicy: Owner
  data: {{- toYaml .data | nindent 4 }}
{{- end -}}
