{{- define "common.pod-spec" -}}
serviceAccountName: {{ .serviceAccountName }}
automountServiceAccountToken: {{ .automountServiceAccountToken }}
{{- if .hostAliases }}
hostAliases: {{- toYaml .hostAliases | nindent 2 }}
{{- end }}
{{- if .affinity }}
affinity: {{- toYaml .affinity | nindent 2 }}
{{- end }}
hostNetwork: {{ .hostNetwork }}
hostIPC: {{ .hostIPC }}
{{- if .dnsPolicy  }}
dnsPolicy: {{ .dnsPolicy }}
{{- end }}
{{- if .dnsConfig }}
dnsConfig: {{- toYaml .dnsConfig | nindent 2 }}
{{- end }}
{{- if .priorityClassName }}
priorityClassName: {{ .priorityClassName }}
{{- end }}
{{- if .nodeSelector }}
nodeSelector: {{- toYaml .nodeSelector | nindent 2 }}
{{- end }}
{{- if .tolerations }}
tolerations: {{- toYaml .tolerations | nindent 2 }}
{{- end }}
{{- if .schedulerName }}
schedulerName: {{ .schedulerName }}
{{- end }}
{{- if .imagePullSecrets }}
imagePullSecrets: {{- toYaml .imagePullSecrets | nindent 2 }}
{{- end }}
{{- if .securityContext }}
securityContext: {{- toYaml .securityContext | nindent 2 }}
{{- end }}
{{- if .terminationGracePeriodSeconds }}
terminationGracePeriodSeconds: {{ .terminationGracePeriodSeconds }}
{{- end }}
restartPolicy: {{ .restartPolicy }}
enableServiceLinks: false
{{- if .initContainers }}
initContainers: {{- include "common.containers" (dict "containers" .initContainers "common" .common) | default "[]" | nindent 2 }}
{{- end }}
containers: {{- include "common.containers" (dict "containers" .containers "common" .common) | default "[]" | nindent 2 }}
{{- if .volumes }}
volumes: {{- toYaml .volumes | nindent 2 }}
{{- end }}
{{- end }}
