{{- define "common.secretstore" -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata: {{- include "common.metadata" . | nindent 2 }}
spec:
  provider: {{- toYaml .provider | nindent 4 }}
{{- end -}}
