{{- range $k, $v := .Values.certificates -}}
{{- if not (eq $v nil) }}
{{ tpl (include "common.certificate" (mergeOverwrite (deepCopy $.Values.common.certificate) $v (dict "name" $k "common" $.Values.common "Values" $.Values))) (merge (dict "name" $k "Template" (dict "BasePath" "<inline>" "Name" "<noname>")) $) }}
{{- end -}}
{{- end -}}
