{{- range $k, $v := .Values.deployments }}
{{- if $v }}
{{- tpl (include "common.deployment" (mergeOverwrite (deepCopy $.Values.common.deployment) $v (dict "name" $k "common" $.Values.common "Values" $.Values))) (merge (dict "Template" (dict "BasePath" "<inline>" "Name" "<noname>")) $) }}
{{- end }}
{{- end }}
