{{- range $k, $v := .Values.deployments }}
{{- if $v }}
{{- include "common.deployment" (mergeOverwrite (deepCopy $.Values.common.deployment) $v (dict "name" (tpl $k (dict "Values" $.Values "Template" (dict "BasePath" "<inline>" "Name" "<noname>"))) "common" $.Values.common "Values" $.Values)) }}
{{- end }}
{{- end }}
