{{- range $k, $v := .Values.deployments -}}
{{- $deployment := mergeOverwrite (deepCopy $.Values.common.deployment) $v (dict "name" $k "common" $.Values.common "Values" $.Values) -}}
{{- if and (not (eq $v nil)) ($deployment.autoscaling.enabled) }}
{{- $hpa := (mergeOverwrite (deepCopy $deployment.autoscaling) (dict "target" (dict "type" "Deployment" "name" $k))) }}
{{ include "common.render" (dict "type" "horizontalPodAutoscaler" "name" $k "spec" $hpa "$" $) }}
{{- end -}}
{{- end -}}

{{- range $k, $v := .Values.horizontalPodAutoscalers -}}
{{- if not (eq $v nil) }}
{{ include "common.render" (dict "type" "horizontalPodAutoscaler" "name" $k "spec" $v "$" $) }}
{{- end -}}
{{- end -}}
