{{- range $k, $v := .Values.httpRoutes -}}
{{- if not (eq $v nil) }}
{{ tpl (include "common.httproute" (mergeOverwrite (deepCopy $.Values.common.httpRoute) $v (dict "name" $k "common" $.Values.common "Values" $.Values))) (merge (dict "Template" (dict "BasePath" "<inline>" "Name" "<noname>")) $) }}
{{- end -}}
{{- end -}}
