{{- range $k, $v := .Values.services }}
{{- if $v }}
{{- tpl (include "common.service" (mergeOverwrite (deepCopy $.Values.common.service) $v (dict "name" $k "common" $.Values.common))) (merge (dict "Template" (dict "BasePath" "<inline>" "Name" "<noname>")) $) }}
{{- end }}
{{- end }}
