{{- range $k, $v := .Values.serviceAccounts -}}
{{- if not (eq $v nil) }}
{{ tpl (include "common.serviceaccount" (mergeOverwrite (deepCopy $.Values.common.serviceAccount) $v (dict "name" $k "common" $.Values.common "Values" $.Values))) (merge (dict "Template" (dict "BasePath" "<inline>" "Name" "<noname>")) $) }}
{{- end -}}
{{- end -}}
