apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-devops-exporter.fullname" . }}
  labels:
    {{- include "azure-devops-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $secretName, $secretValue := .Values.secret }}
  {{ $secretName }}: {{ $secretValue | b64enc | quote }}
  {{- end }}
