{{- $secretStore := ternary "SecretStore" "ClusterSecretStore" .Values.externalSecretStore.create -}}
{{- $secretStoreName := ternary .Values.externalSecretStore.name .Values.externalSecret.secretStoreName .Values.externalSecretStore.create -}}
{{- if .Values.externalSecret.create -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name | default (printf "%s" (include "azure-devops-agents.fullname" .)) }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ $secretStore }}
    name: {{ $secretStoreName }}
  target:
    name: {{ .Values.externalSecret.secretName | default (printf "%s" (include "azure-devops-agents.fullname" .)) }}
  data:
    - secretKey: AZP_TOKEN
      remoteRef:
        key: {{ .Values.externalSecret.remoteKey }}
{{- end }}
