{{- range .Values.secretEnvs }}
  {{- include "common-templates.externalSecret.tpl" dict(
    "name" (printf "%s-%s" (include "tomtom-base-chart.fullname" $) "env-es" )
    "secretStore" .secretStore
    "mappings" .secrets
  ) }}
{{- end }}

{{- range .Values.secretFiles }}
  {{- include "common-templates.externalSecret.tpl" dict(
    "name" (printf "%s-%s" (include "tomtom-base-chart.fullname" $) "file-es" )
    "secretStore" .secretStore
    "mappings" .files
  ) }}
{{- end }}

{{- range .Values.image.externalPullSecret }}
  {{- include "common-templates.externalSecret.tpl" dict(
    "name" (printf "%s-%s" (include "tomtom-base-chart.fullname" $) "imagepullsecret" )
    "secretStore" .secretStore
    "mappings" (.secretKey)
    "isRegistryCredential" true
  ) }}
{{- end }}