{{- define "common.application" -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: {{- include "common.metadata" . | nindent 2 }}
{{- if and (not .syncPolicy.automated.prune) (not .syncPolicy.automated.selfHeal) (not .syncPolicy.automated.allowEmpty) }}{{ $_ := set .syncPolicy "automated" dict }}{{ end }}
{{- if .sources }}{{ $_ := set . "sources" (include "common.to-list" (dict "$values" .sources "$keyAt" nil) | fromYamlArray) }}{{ end }}
{{- $destinationDefaults := dict "namespace" .namespace }}
{{ if .destination }}{{ $_ := mergeOverwrite .destination $destinationDefaults (deepCopy .destination) }}{{ end }}
spec: {{- include "common.render-spec" . | nindent 2 }}
{{- end -}}
