{{- define "common.argocdrollout" -}}
{{- if not .spec.workloadRef -}}
{{- /* extra-logic: set pod labels from spec.selector.matchLabels */}}
{{- $pod := merge .spec.template (dict "metadata" (dict "labels" .spec.selector.matchLabels)) }}
{{- $_ := merge $pod (include "common.render-metadata" $pod.metadata | fromYaml) }}
{{- $_ := include "common.pod" (merge $pod (dict "common" .common)) }}
{{- else -}}
{{ $_ := unset .spec "template" }}
{{- end -}}
{{- end -}}
