{{- define "common.certificate" -}}
{{- /* reducers: default to own name for spec.target.secretName */}}
{{- $defaults := dict "secretName" .name }}
{{- if .spec.target }}{{ $_ := mergeOverwrite .spec $defaults (deepCopy .spec) }}{{ end }}
{{- end -}}
