{{- define "common.certificate" -}}
{{- /* reducers: default to metadata.name for spec.target.secretName */}}
{{- $defaults := dict "secretName" .metadata.name }}
{{- if not .spec.secretName }}{{ $_ := merge .spec $defaults }}{{ end }}
{{- end -}}
