{{- define "common.certificate" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: {{- include "common.metadata" . | nindent 2 }}
spec:
  secretName: {{ .secretName | default .name }}
  {{- include "common.render-spec" (omit . "secretName") | nindent 2 }}
{{- end }}
