{{- define "common.certificate" -}}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata: {{- include "common.metadata" . | nindent 2 }}
spec:
  secretName: {{ .name }}
  {{- if .commonName }}
  commonName: {{ .commonName }}
  {{- end }}
  dnsNames: {{- toYaml .dnsNames | nindent 4 }}
  usages:
    - digital signature
    - key encipherment
  issuerRef: {{- toYaml .issuerRef | nindent 4 }}
{{- end }}
