{{- define "common.cronjob" -}}
{{- $pod := mergeOverwrite (deepCopy .common.pod) .pod (dict "common" .common) }}
---
apiVersion: batch/v1
kind: CronJob
metadata: {{- include "common.metadata" . | nindent 2 }}
spec:
  concurrencyPolicy: {{ .concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit }}
  schedule: "{{ .schedule }}"
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit }}
  suspend: {{ .suspend }}
  jobTemplate:
    spec:
      template:
        spec: {{- include "common.pod-spec" $pod | nindent 10 }}
{{- end }}
