{{- define "common.cronjob" -}}
{{- $pod := mergeOverwrite (deepCopy .common.pod) (.pod | default dict) (dict "common" .common) }}
---
apiVersion: batch/v1
kind: CronJob
metadata: {{- include "common.metadata" . | nindent 2 }}
{{- $podTemplate := (dict "metadata" (include "common.metadata" $pod | fromYaml) "spec" (include "common.pod-spec" $pod | fromYaml)) }}
{{ $_ := set . "jobTemplate" (dict "spec" (dict "template" $podTemplate)) }}
spec: {{- include "common.render-spec" (omit . "pod") | nindent 2 }}
{{- end }}
