{{- define "common.cronjob" -}}
{{- /* extra-logic: set pod defaults from common.pod */}}
{{- $pod := merge .spec.jobTemplate.spec.template .common.pod (dict "common" .common) }}
{{- $_ := merge .spec.jobTemplate.spec.template (dict "metadata" (include "common.render-metadata" $pod | fromYaml)) }}
{{- $_ := include "common.pod" $pod }}
{{- end -}}
