{{- define "common.cronjob" -}}
{{- $pod := .spec.jobTemplate.spec.template }}
{{- $_ := merge $pod (include "common.render-metadata" $pod.metadata | fromYaml) }}
{{- $_ := include "common.pod" (merge $pod (dict "common" .common)) }}
{{- end -}}
