{{- define "common.deployment" -}}
{{- $pod := mergeOverwrite (deepCopy .common.pod) (.pod | default dict) (dict "labels" .selector.matchLabels "common" .common) }}
{{/* extra-logic: distinguish zero and null spec.replicas values */}}
{{- if not (or .replicas (eq .replicas 0.0)) }}{{ $_ := unset . "replicas" }}{{ end }}
{{- $podTemplate := (dict "metadata" (include "common.metadata" $pod | fromYaml) "spec" (include "common.pod-spec" $pod | fromYaml)) }}
{{ $_ := set . "template" $podTemplate }}
spec: {{- include "common.render-spec" (omit . "pod") | nindent 2 }}
{{- end -}}
