{{- define "common.deployment" -}}
{{- $pod := mergeOverwrite (deepCopy .common.pod) .pod (dict "labels" .selector.matchLabels "common" .common) }}
---
apiVersion: apps/v1
kind: Deployment
metadata: {{- include "common.metadata" . | nindent 2 }}
{{- if not (or .replicas (eq .replicas 0.0)) }}{{ $_ := unset . "replicas" }}{{ end }}
{{- $podTemplate := (dict "metadata" (include "common.metadata" $pod | fromYaml) "spec" (include "common.pod-spec" $pod | fromYaml)) }}
{{ $_ := set . "template" $podTemplate }}
spec: {{- include "common.render-spec" (omit . "pod") | nindent 2 }}
{{- end -}}
