{{- define "common.externalsecret" -}}
{{- /* reducers: default to own name for spec.target.name */}}
{{- $targetDefaults := dict "name" .name }}
{{- if .spec.target }}{{ $_ := mergeOverwrite .spec.target $targetDefaults (deepCopy .spec.target) }}{{ end }}
{{- /* dict-to-list: expand spec.data dict to list of {{remoteRef, key}, secretKey} objects (if dict value is string), or a copy of dict's value */}}
{{- $_ := set .spec "data" (include "common.to-list" (dict "$values" .spec.data "$keyAt" "secretKey" "$valueAt" "remoteRef.key") | fromYamlArray) }}
{{- end -}}
