{{- define "common.externalsecret" -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: {{- include "common.metadata" . | nindent 2 }}
spec:
  refreshInterval: 1h
  secretStoreRef: {{- toYaml .secretStoreRef | nindent 4 }}
  target:
    {{- if .target.template }}
    template: {{- toYaml .target.template | nindent 6 }}
    {{- end }}
    name: {{ .target.name | default .name }}
    creationPolicy: {{ .target.creationPolicy }}
  data: {{- include "common.to-list" (dict "$values" .data "$keyAt" "secretKey" "$valueAt" "remoteRef.key") | nindent 4 }}
{{- end -}}
