{{- define "common.externalsecret" -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: {{- include "common.metadata" . | nindent 2 }}
{{/* reducers: default to own name for spec.target.name */}}
{{- $targetDefaults := dict "name" .name }}
{{ if .target }}{{ $_ := mergeOverwrite .target $targetDefaults (deepCopy .target) }}{{ end }}
{{/* dict-to-list: expand spec.data dict to list of {{remoteRef, key}, secretKey} objects (if dict value is string), or a copy of dict's value */}}
{{- $_ := set . "data" (include "common.to-list" (dict "$values" .data "$keyAt" "secretKey" "$valueAt" "remoteRef.key") | fromYamlArray) }}
spec: {{- include "common.render-spec" . | nindent 2 }}
{{- end -}}
