{{- define "common.externalsecret" -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata: {{- include "common.metadata" . | nindent 2 }}
{{- $targetDefaults := dict "name" .name }}
{{ if .target }}{{ $_ := mergeOverwrite .target $targetDefaults (deepCopy .target) }}{{ end }}
{{- $_ := set . "data" (include "common.to-list" (dict "$values" .data "$keyAt" "secretKey" "$valueAt" "remoteRef.key") | fromYamlArray) }}
spec: {{- include "common.render-spec" . | nindent 2 }}
{{- end -}}
