{{- define "common.httproute" -}}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata: {{- include "common.metadata" . | nindent 2 }}
spec:
  parentRefs:
  {{- range .parentRefs }}
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: {{ .name }}
    namespace: istio-ingress
    port: {{ .port | default 443 }}
  {{- end }}
  hostnames: {{- toYaml .hostnames | nindent 4 }}
  rules: {{- toYaml .rules | nindent 4 }}
{{- end -}}
