{{- define "common.httproute" -}}
{{- /* reducers: default to own name for spec.parentRefs.*.name (with other standard defaults) */}}
{{- $parentRefDefaults := dict "group" "gateway.networking.k8s.io" "kind" "Gateway" "namespace" "istio-ingress" "port" 443 "name" .name }}
{{- range $x := .spec.parentRefs }}{{ $_ := mergeOverwrite $x $parentRefDefaults (deepCopy $x) }}{{ end }}
{{- end -}}
