{{- define "common.istiovirtualservice" -}}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata: {{- include "common.metadata" . | nindent 2 }}
spec: {{- include "common.render-spec" . | nindent 2 }}
{{- end -}}
