{{- define "common.pod" -}}
{{- /* dict-to-list: expand initContainers dict to list of objects, with dict keys in name field */}}
{{- if .spec.initContainers }}{{ $_ := set .spec "initContainers" (include "common.to-list" (dict "$values" .spec.initContainers "$common" .common.container "$helper" "common.container") | fromYamlArray) }}{{ end }}
{{- /* dict-to-list: expand containers dict to list of objects, with dict keys in name field */}}
{{- $_ := set .spec "containers" (include "common.to-list" (dict "$values" .spec.containers "$common" .common.container "$helper" "common.container") | fromYamlArray) }}
{{- /* dict-to-list: expand volumes dict to list of objects, with dict keys in name field */}}
{{- if .spec.volumes }}{{ $_ := set .spec "volumes" (include "common.to-list" .spec.volumes | fromYamlArray) }}{{ end }}
{{- $_ := unset . "common" }}
{{- end -}}
