{{- define "common.poddisruptionbudget" -}}
{{- /* extra-logic: can use only one of spec.minAvailable or spec.maxUnavailable, but not both at the same time */}}
{{- if not (eq .spec.minAvailable nil) }}{{ $_ := unset .spec "maxUnavailable" }}{{ end }}
{{- end -}}
