{{- define "common.pod-spec" -}}
{{- if .initContainers }}{{ $_ := set . "initContainers" (include "common.to-list" (dict "$values" .initContainers "$common" .common.container "$helper" "common.container-spec") | fromYamlArray) }}{{ end }}
{{- $_ := set . "containers" (include "common.to-list" (dict "$values" .containers "$common" .common.container "$helper" "common.container-spec") | fromYamlArray) }}
{{- if .volumes }}{{ $_ := set . "volumes" (include "common.to-list" .volumes | fromYamlArray) }}{{ end }}
{{- include "common.render-spec" . }}
{{- end }}
