{{- define "common.poddisruptionbudget" -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: {{- include "common.metadata" . | nindent 2 }}
{{- $spec := . }}
{{- if not (eq $spec.minAvailable nil) }}
{{- $spec := omit $spec "maxUnavailable" }}
{{- end }}
spec: {{- include "common.to-yaml" $spec | nindent 2 }}
{{- end }}
