{{- define "common.poddisruptionbudget" -}}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata: {{- include "common.metadata" . | nindent 2 }}
{{- if not (eq .minAvailable nil) }}{{ $_ := unset . "maxUnavailable" }}{{ end }}
spec: {{- include "common.render-spec" . | nindent 2 }}
{{- end }}
