{{- define "common.service" -}}
{{/* dict-to-list: expand spec.ports dict to list of objects, with dict keys in name field */}}
{{- $_ := set . "ports" (include "common.to-list" .ports | fromYamlArray) }}
spec: {{- include "common.render-spec" . | nindent 2 }}
{{- end }}
