{{- define "common.service" -}}
{{- /* dict-to-list: expand spec.ports dict to list of objects, with dict keys in name field */}}
{{- $_ := set .spec "ports" (include "common.to-list" .spec.ports | fromYamlArray) }}
{{- end -}}
