{{- define "common.service" -}}
---
apiVersion: v1
kind: Service
metadata: {{- include "common.metadata" . | nindent 2 }}
{{- $_ := set . "ports" (include "common.to-list" .ports | fromYamlArray) }}
spec: {{- include "common.render-spec" . | nindent 2 }}
{{- end }}
