{{- define "common.vmalertmanagerconfig" -}}
{{- /* dict-to-list: expand spec.route.routes dict to list of objects, with dict keys in receiver field */}}
{{- /* reducers: default spec.route.routes.*.continue to true */}}
{{- $routes := .spec.route.routes | default dict }}
{{- $routeDefaults := dict "continue" true }}
{{- $_ := set .spec.route "routes" (include "common.to-list" (dict "$values" $routes "$common" $routeDefaults "$keyAt" "receiver") | fromYamlArray) }}
{{- /* dict-to-list: expand spec.receivers dict to list of objects, with dict keys in name field */}}
{{- $_ := set .spec "receivers" (include "common.to-list" .spec.receivers | fromYamlArray) }}
{{- /* dict-to-list: expand spec.receivers.* dicts to lists of objects, discarding keys */}}
{{- range $r := .spec.receivers }}{{ range $k, $v := $r }}{{ if not (eq $k "name") }}{{ $_ := set $r $k (include "common.to-list" (dict "$values" $v "$keyAt" nil) | fromYamlArray) }}{{ end }}{{ end }}{{ end }}
{{- end -}}
