{{- define "common.vmalertmanagerconfig" -}}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanagerConfig
metadata: {{- include "common.metadata" . | nindent 2 }}
{{- $routes := .route.routes | default dict }}
{{- $routeDefaults := dict "continue" true }}
{{- $_ := set .route "routes" (include "common.to-list" (dict "$values" $routes "$common" $routeDefaults "$keyAt" "receiver") | fromYamlArray) }}
{{- $_ := set . "receivers" (include "common.to-list" .receivers | fromYamlArray) }}
{{- range $r := .receivers }}{{ range $k, $v := $r }}{{ if not (eq $k "name") }}{{ $_ := set $r $k (include "common.to-list" (dict "$values" $v "$keyAt" nil) | fromYamlArray) }}{{ end }}{{ end }}{{ end }}
spec: {{- include "common.render-spec" . | nindent 2 }}
{{- end -}}
