{{- define "common.vmrule" -}}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
metadata: {{- include "common.metadata" . | nindent 2 }}
{{- range $k, $v := .groups }}{{- $_ := set $v "rules" (include "common.to-list" (dict "$values" .rules "$keyAt" "alert") | fromYamlArray) }}{{ end }}
{{- $_ := set . "groups" (include "common.to-list" .groups | fromYamlArray) }}
spec: {{- include "common.render-spec" . | nindent 2 }}
{{- end -}}
