{{- range $k, $v := .Values.horizontalPodAutoscalers -}}
{{- if not (eq $v nil) }}
{{ include "common.render" (dict "type" "horizontalPodAutoscaler" "name" $k "spec" $v "$" $) }}
{{- end -}}
{{- end -}}
