{{- if .Values.advancedSettings.externalSecretStore.create -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.advancedSettings.externalSecretStore.name }}
spec:
  {{- with .Values.advancedSettings.externalSecretStore.provider }}
  provider:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
