{{- if .Values.basicSettings.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tomtom-base-chart.fullname" . }}
  labels:
    {{- include "tomtom-base-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tomtom-base-chart.fullname" . }}
  minReplicas: {{ .Values.basicSettings.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.basicSettings.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.basicSettings.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.basicSettings.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.basicSettings.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.basicSettings.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.basicSettings.autoscaling.behavior }}  # Check if behavior exists
  behavior:
    {{- if .Values.basicSettings.autoscaling.behavior.scaleDown }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.basicSettings.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
        {{- range .Values.basicSettings.autoscaling.behavior.scaleDown.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
    {{- end }}
    {{- if .Values.basicSettings.autoscaling.behavior.scaleUp }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.basicSettings.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        {{- range .Values.basicSettings.autoscaling.behavior.scaleUp.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
      {{- if .Values.basicSettings.autoscaling.behavior.scaleUp.selectPolicy }}
      selectPolicy: {{ .Values.basicSettings.autoscaling.behavior.scaleUp.selectPolicy }}
      {{- end }}
    {{- end }}
  {{- end }} 
{{- end }}
