{{- if and .Values.basicSettings.image.pullSecret (not .Values.advancedSettings.imagePullSecrets) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-imagepullsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.basicSettings.image.pullSecret.secretStore }}
    kind: SecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: "{{ `{{ .imagepullsecret }}` }}"
    name: {{ .Release.Name }}-imagepullsecret
    creationPolicy: Owner
  data:
  - secretKey: imagepullsecret
    remoteRef:
      key: {{ .Values.basicSettings.image.pullSecret.secretKey }}
{{- end }}

