{{- if and .Values.basicSettings.fqdn (eq .Values.advancedSettings.ingress.className "traefik") -}}
{{- $ingressFullName := include "tomtom-base-chart.fullname" . -}}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $ingressFullName }}-ipallowlist
spec:
  ipWhiteList:
    sourceRange:
    - 0.0.0.0/0
{{- end }}