---
name: Test App Chart

on:
  push:
    paths:
      - charts/app/**
  workflow_dispatch:
    inputs:

permissions:
  id-token: write
  contents: read

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: d3adb5/helm-unittest-action@v2
        with:
          charts: charts/app
      - run: helm lint ./charts/app --quiet
