apiVersion: v2
name: ghc-secret-store
description: TomTom Golden Helm Chart for deployments
type: application
version: 0.1.0
dependencies:
  - name: common-templates
    version: 0.1.0
    repository: file://../common-templates